import { useMemo, useState } from 'react';
import type { Lab } from '../../validation/useValidationLab';
import type { DiagnosisMetrics, PassMetrics, RecordPass } from '../../validation/types';
import { accuracy } from '../../validation/aggregate';
import { Chips, Pagination } from './LabRecords';
export const percentage = (value: number | null) => value === null ? 'Not reported' : `${(value*100).toFixed(1)}%`;
const delta = (a: number | null, b: number | null) => a === null || b === null ? '—' : `${b-a > 0 ? '+' : ''}${((b-a)*100).toFixed(1)} pp`;
export function StatCards({ items }: { items: [string, string | number][] }) { return <div className="lab-stat-grid">{items.map(([label,value]) => <div className="lab-stat" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>; }
function Metric({ title, baseline, latent }: { title: string; baseline: number | null; latent: number | null }) {
  return <article className="lab-metric"><h3>{title}</h3>{([['Without latent',baseline],['With latent',latent]] as const).map(([label,value]) => <div className="lab-metric-row" key={label}><div><span>{label}</span><strong>{percentage(value)}</strong></div><div className={'lab-bar ' + (label === 'With latent' ? 'lab-bar-latent' : '')} aria-hidden="true"><i style={{ width: `${(value ?? 0)*100}%` }} /></div></div>)}<p className={baseline !== null && latent !== null && latent < baseline ? 'lab-error-text' : ''}>Difference <strong>{delta(baseline,latent)}</strong></p></article>;
}
type SortKey = 'diagnosis' | 'support' | 'baseline1' | 'latent1' | 'delta1' | 'baseline3' | 'latent3' | 'delta3' | 'baseline5' | 'latent5';
function DiagnosisTable({ lab, onSelect }: { lab: Lab; onSelect: (diagnosis: string) => void }) {
  const [search,setSearch] = useState(''), [minimum,setMinimum] = useState(1), [filter,setFilter] = useState('all'), [sort,setSort] = useState<SortKey>('support'), [descending,setDescending] = useState(true), [page,setPage] = useState(0);
  const score = (row: DiagnosisMetrics, key: SortKey) => {
    if (key === 'diagnosis') return row.diagnosis;
    if (key === 'support') return row.support;
    const k = key.endsWith('1') ? 'top_1_correct' : key.endsWith('3') ? 'top_3_correct' : 'top_5_correct';
    if (key.startsWith('delta')) return row.support ? (row.with_latent[k]-row.without_latent[k])/row.support : 0;
    return (key.startsWith('baseline') ? row.without_latent[k] : row.with_latent[k]) / (row.support || 1);
  };
  const rows = [...lab.aggregate.per_diagnosis].filter(row => row.diagnosis.toLowerCase().includes(search.toLowerCase()) && row.support >= minimum && (filter === 'all' || (filter === 'worse' ? row.with_latent.top_1_correct < row.without_latent.top_1_correct : row.with_latent.top_1_correct > row.without_latent.top_1_correct))).sort((a,b) => { const x=score(a,sort), y=score(b,sort); return (typeof x === 'string' && typeof y === 'string' ? x.localeCompare(y) : Number(x)-Number(y))*(descending ? -1 : 1); });
  const current = Math.min(page, Math.max(0,Math.ceil(rows.length/10)-1));
  const columns: [SortKey,string][] = [['diagnosis','Diagnosis'],['support','Support'],['baseline1','Baseline Top-1'],['latent1','Latent Top-1'],['delta1','Δ Top-1'],['baseline3','Baseline Top-3'],['latent3','Latent Top-3'],['delta3','Δ Top-3'],['baseline5','Baseline Top-5'],['latent5','Latent Top-5']];
  return <section className="lab-card"><h2>Per-diagnosis analysis</h2><p>Compare each diagnosis separately. Click a diagnosis to inspect its records.</p>{!lab.aggregate.diagnosisDetailsComplete && <p className="lab-warning">Per-diagnosis details are incomplete or were not returned by the service. Only reported counts are shown.</p>}<div className="lab-filters"><label>Search diagnosis<input value={search} onChange={e => { setSearch(e.target.value); setPage(0); }} /></label><label>Minimum support<input type="number" min="1" value={minimum} onChange={e => { setMinimum(Math.max(1,e.target.valueAsNumber || 1)); setPage(0); }} /></label><label>Top-1 change<select value={filter} onChange={e => { setFilter(e.target.value); setPage(0); }}><option value="all">All diagnoses</option><option value="worse">Worse with latent</option><option value="better">Better with latent</option></select></label></div>
    <div className="lab-table-scroll" tabIndex={0} role="region" aria-label="Per-diagnosis metrics"><table className="lab-table"><thead><tr>{columns.map(([key,label]) => <th key={key} aria-sort={sort === key ? descending ? 'descending' : 'ascending' : 'none'}><button onClick={() => { setSort(key); setDescending(sort === key ? !descending : key !== 'diagnosis'); setPage(0); }}>{label}{sort === key ? descending ? ' ↓' : ' ↑' : ''}</button></th>)}</tr></thead><tbody>{rows.slice(current*10,current*10+10).map(row => <tr key={row.diagnosis}>{columns.map(([key]) => <td key={key}>{key === 'diagnosis' ? <button className="text-button" onClick={() => onSelect(row.diagnosis)}>{row.diagnosis}</button> : key === 'support' ? row.support : key.startsWith('delta') ? `${Number(score(row,key)) > 0 ? '+' : ''}${(Number(score(row,key))*100).toFixed(1)} pp` : percentage(row.support ? Number(score(row,key)) : null)}</td>)}</tr>)}</tbody></table></div><Pagination page={current} count={rows.length} onChange={setPage} />
  </section>;
}
function Predictions({ title, value }: { title: string; value?: RecordPass }) {
  return <div><h3>{title}</h3>{value ? <><ol className="lab-predictions">{value.diagnoses.map(item => <li key={item.rank} value={item.rank}>{item.diagnosis}</li>)}</ol>{!value.diagnoses.length && <p>No ranked candidates returned.</p>}<p>Ground-truth rank: <strong>{value.ground_truth_rank ?? 'Not reported / not ranked'}</strong></p></> : <p>Record-level predictions were not returned by the service.</p>}</div>;
}
function RecordExplorer({ lab, diagnosis, setDiagnosis }: { lab: Lab; diagnosis: string; setDiagnosis: (value: string) => void }) {
  const [filter,setFilter] = useState('all'), [search,setSearch] = useState(''), [page,setPage] = useState(0);
  const details = useMemo(() => new Map(lab.aggregate.records.map(row => [row.record_index,row])), [lab.aggregate.records]);
  const rows = lab.prepared.filter(row => (!diagnosis || row.record.concluded_diagnosis === diagnosis) && (!search || [row.record.concluded_diagnosis,...row.record.current_symptoms,...row.record.latent_symptoms].join(' ').toLowerCase().includes(search.toLowerCase())) && (filter === 'all' || (filter === 'none' ? !row.record.latent_symptoms.length : details.get(row.index)?.outcome === filter)));
  const current = Math.min(page, Math.max(0,rows.length-1)), row = rows[current], detail = row ? details.get(row.index) : undefined;
  return <section id="lab-record-explorer" className="lab-card"><h2>Record Explorer</h2><p>Inspect rank changes without treating generated symptoms as observations.</p><div className="lab-filters"><label>Search<input value={search} onChange={e => { setSearch(e.target.value); setPage(0); }} /></label><label>Outcome<select value={filter} onChange={e => { setFilter(e.target.value); setPage(0); }}>{[['all','All records'],['improved','Improved'],['worsened','Worsened'],['unchanged','Unchanged'],['unknown','Unknown ground truth'],['none','No latent symptoms']].map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label>{diagnosis && <button className="secondary-button" onClick={() => setDiagnosis('')}>Clear diagnosis filter: {diagnosis}</button>}</div>
    {row && <><div className="lab-record-heading"><strong>Record #{row.index+1} | {row.record.concluded_diagnosis}</strong><span className={detail?.outcome === 'worsened' ? 'lab-error-text' : ''}>{detail?.outcome ?? 'Outcome not returned'}</span></div><h3>Original symptoms</h3><Chips values={row.record.current_symptoms} /><h3>Generated latent symptoms</h3><Chips values={row.record.latent_symptoms} latent /><div className="lab-before-after"><Predictions title="Without latent" value={detail?.without_latent} /><Predictions title="With latent" value={detail?.with_latent} /></div>{detail && <p>Rank change: {detail.without_latent?.ground_truth_rank ?? '—'} → {detail.with_latent?.ground_truth_rank ?? '—'}. Lower rank is better.</p>}{detail?.unknown_model_features && <><h4>Unknown model features</h4><Chips values={detail.unknown_model_features} /></>}</>}
    {lab.aggregate.records.length < lab.aggregate.summary.records_received && <p className="lab-warning">Some record-level results were not returned. Outcome filters include only records with a reported outcome.</p>}<Pagination page={current} count={rows.length} size={1} onChange={setPage} />
  </section>;
}
export function downloadReport(lab: Lab) {
  const url = URL.createObjectURL(new Blob([JSON.stringify(lab.report(),null,2)], { type: 'application/json' }));
  const anchor = document.createElement('a'); anchor.href = url; anchor.download = `curamate-validation-${new Date().toISOString().replace(/[:.]/g,'-')}.json`; anchor.click(); setTimeout(() => URL.revokeObjectURL(url),1000);
}
export function LabResults({ lab }: { lab: Lab }) {
  const [diagnosis,setDiagnosis] = useState(''); const summary = lab.aggregate.summary;
  const rankValue = (value: number | null | undefined) => value == null ? 'Not reported' : value.toFixed(2);
  return <><section className="lab-card"><div className="lab-section-heading"><div><span className="lab-eyebrow">{lab.phase === 'results' ? 'VALIDATION COMPLETE' : 'PARTIAL RESULTS'}</span><h2>{summary.records_received.toLocaleString()} records processed</h2><p>{summary.records_evaluated.toLocaleString()} records evaluated | {summary.unknown_ground_truth_records} unknown ground truths excluded from accuracy</p></div><button className="secondary-button" onClick={() => downloadReport(lab)}>Download Evaluation Report</button></div><div className="lab-metric-grid">{([1,3,5] as const).map(k => { const key = `top_${k}_correct` as keyof Pick<PassMetrics,'top_1_correct'|'top_3_correct'|'top_5_correct'>; return <Metric key={k} title={`Top-${k} accuracy`} baseline={accuracy(summary.without_latent[key],summary.records_evaluated)} latent={accuracy(summary.with_latent[key],summary.records_evaluated)} />; })}</div><p className="lab-footnote">Differences are percentage points (pp). Accuracy uses evaluated records only; missing ground-truth labels are not counted as wrong predictions.</p></section>
    <section className="lab-card"><h2>Rank outcomes</h2><p>Improved means the known diagnosis moved to a better rank; worsened means a worse rank.</p><StatCards items={[["Improved",summary.comparison.improved_records],["Worsened",summary.comparison.worsened_records],["Unchanged",summary.comparison.unchanged_records]]} /><h3>Average ground-truth rank - lower is better</h3><div className="lab-before-after"><div><span>Without latent</span><strong className="lab-rank">{rankValue(summary.without_latent.average_ground_truth_rank)}</strong></div><div><span>With latent</span><strong className="lab-rank">{rankValue(summary.with_latent.average_ground_truth_rank)}</strong></div></div>{(summary.without_latent.median_ground_truth_rank != null || summary.with_latent.median_ground_truth_rank != null) && <p>Median rank: without latent {rankValue(summary.without_latent.median_ground_truth_rank)} | with latent {rankValue(summary.with_latent.median_ground_truth_rank)}</p>}</section>
    <DiagnosisTable lab={lab} onSelect={value => { setDiagnosis(value); document.getElementById('lab-record-explorer')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); }} /><RecordExplorer lab={lab} diagnosis={diagnosis} setDiagnosis={setDiagnosis} />
    <section className="lab-card"><h2>Data quality</h2><StatCards items={[["Unknown ground-truth diagnoses (records)",summary.unknown_ground_truth_records],["Unknown model features (backend)",summary.unknown_model_features ?? 'Not reported'],["Invalid input records",lab.rows.length-lab.validRows.length],["Records with no latent symptoms",lab.prepared.filter(row => !row.record.latent_symptoms.length).length],["Successfully evaluated",summary.records_evaluated],["Records with unknown local features",lab.prepared.filter(row => row.generation.unknownSymptoms.length || row.generation.unknownContexts.length).length],["Truncated latent searches",lab.prepared.filter(row => row.generation.truncated).length]]} /></section>
    <div className="lab-actions"><button className="secondary-button" disabled={lab.busy} onClick={lab.again}>Run Again With Different Thresholds</button><button className="secondary-button" disabled={lab.busy} onClick={lab.newDataset}>Upload New Dataset</button></div>
  </>;
}
